pick_1:
  ros__parameters:
    plugins:
      - plansys2_pick_bt_node
      - plansys2_place_bt_node
    waypoints: ["fridge_zone", "pantry_zone", "watertap_zone", "cooking_zone", "recharge_zone"]
    waypoint_coords:
      # x, y, theta
      fridge_zone: [6.64, -3.19, 0.907]
      pantry_zone: [4.854, 1.747, 2.445]  
      watertap_zone: [2.787, -0.328, -2.739]  
      cooking_zone: [5.086, -1.380, 0.907]
      recharge_zone: [8.758, -0.528, -2.891]
place_1:
  ros__parameters:
    plugins:
      - plansys2_place_bt_node
    place_locations: [
      "foodtray_sz_0",
      "foodtray_sz_1",
      "foodtray_sz_2",
      "foodtray_sz_3",
      "foodtray_sz_4",
      "foodtray_sz_5"
    ]
    place_locations_coords:
      # x, y, z
      foodtray_sz_0: [1.92, -0.62, 0.4]
      foodtray_sz_1: [1.92, -0.44, 0.4]
      foodtray_sz_2: [1.71, -0.62, 0.4]
      foodtray_sz_3: [1.57, -0.62, 0.4]
      foodtray_sz_4: [1.71, -0.44, 0.4]
      foodtray_sz_5: [1.57, -0.44, 0.4]